# Generated by Django 5.2.3 on 2025-07-04 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quotapackage_quotapurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotapurchase',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_status', models.CharField(default='pending', max_length=50)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
