# Generated by Django 5.2.3 on 2025-07-04 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_quotapurchase_payment_proof_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.quotapackage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gross_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
