# Generated by Django 5.2.3 on 2025-07-28 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_package_alter_transaction_gross_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('analysis', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
