# Generated by Django 5.2.3 on 2025-07-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seoanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('gemini', 'Gemini (Google)'), ('gpt-3.5-turbo', 'GPT-3.5 (OpenAI)'), ('gpt-4-1106-preview', 'GPT-4.1 (OpenAI)')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quota_cost', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Configuration',
                'verbose_name_plural': 'AI Model Configurations',
            },
        ),
    ]
