# Generated by Django 5.2.3 on 2025-07-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aimodelconfig'),
    ]

    operations = [
    ]
