# Generated by Django 5.2.3 on 2025-07-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250728_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Kunci pengaturan', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Nilai pengaturan')),
                ('description', models.TextField(blank=True, help_text='Deskripsi pengaturan')),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['key'],
            },
        ),
    ]
