# Generated by Django 5.2.3 on 2025-07-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(choices=[('serpapi', 'SerpAPI'), ('google_search', 'Google Search API'), ('bing_search', 'Bing Search API')], max_length=50, unique=True)),
                ('api_key', models.CharField(help_text='API Key untuk layanan', max_length=255)),
                ('base_url', models.URLField(help_text='Base URL untuk API', max_length=500)),
                ('max_results', models.PositiveIntegerField(default=100, help_text='Jumlah maksimal hasil')),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Timeout dalam detik')),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif API')),
                ('description', models.TextField(blank=True, help_text='Deskripsi konfigurasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
                'ordering': ['api_name'],
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
