# Generated by Django 5.2.3 on 2025-08-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_apiconfig_delete_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiConfig',
        ),
    ]
